name: Test code with shellcheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
